version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=https://interferometric-unsymmetrically-anette.ngrok-free.dev
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://interferometric-unsymmetrically-anette.ngrok-free.dev/
    volumes:
      - ./n8n_data:/home/node/.n8n
